spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/task_manager
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog-master.xml