jwt:
  secret: mysecret
  lifetime: 30m
spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASS:123}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:task_manager}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: db/changelog/changelog-master.xml